# Generated by Django 6.1.1 on 2026-09-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.CharField(choices=[('physical', 'Physical'), ('social', 'Social'), ('creative', 'Creative'), ('exploration', 'Exploration')], default='physical', max_length=20),
            preserve_default=False,
        ),
    ]
