# Generated by Django 6.0.8 on 2026-09-25 06:52

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_category'),
    ]

    operations = [
        VectorExtension()
    ]
