# Generated by Django 6.0.8 on 2026-09-25 07:02

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
